---
name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          version-file: "my-version-file.yaml"
          skip-on-empty: "false"
          skip-commit: "false"
          fallback-version: "0.4.0"
          # tag_name: ${{ steps.changelog.outputs.tag }}
          # release_name: ${{ steps.changelog.outputs.tag }}
          # body: ${{ steps.changelog.outputs.clean_changelog }}
